/**
 * M2 perf-evidence generator (T2.4) — emits a plausible n-file UiPath coded
 * project for the call-graph pipeline to chew on:
 *
 *   - project.json with the entry point on file 0 (Workflows/Workflow000.cs),
 *   - n workflow classes (~40 lines each): 2-3 service calls, an if + foreach,
 *     a `workflows.<NextClass>(...)` call chaining to the next file (wrapping
 *     at the end), every 7th file a literal `RunWorkflow("Legacy/FlowX.xaml")`
 *     and every 11th a dynamic `RunWorkflow(variable)`,
 *   - 5 shared helper classes called statically (`HelperK.Method(...)`).
 *
 * Content is DETERMINISTIC — every byte is a pure function of (index, n).
 * No randomness, no timestamps: re-running with the same arguments produces
 * an identical tree.
 *
 * Usage:
 *   node scripts/genSampleProject.mjs <n> [outDir=tmp-sample-project]
 *
 * Dev-only: scripts/** is .vscodeignore'd and the default outDir is
 * .gitignore'd.  Plain Node, no TS imports — also imported as a module by
 * scripts/graphPerf.mjs.
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

export const HELPER_COUNT = 5;
export const ENTRY_REL_PATH = 'Workflows/Workflow000.cs';

/** `Workflow007`-style class name for file index `i`. */
export function workflowClassName(i) {
  return `Workflow${String(i).padStart(3, '0')}`;
}

/** Deterministic ~40-line workflow class chaining to the next file. */
function workflowSource(i, n) {
  const cls = workflowClassName(i);
  const next = workflowClassName((i + 1) % n);
  const helper = `Helper${i % HELPER_COUNT}`;
  const lines = [
    `// Generated by scripts/genSampleProject.mjs — workflow ${i + 1} of ${n}.`,
    '// Deterministic content seeded by file index; do not edit by hand.',
    'using System;',
    'using System.Linq;',
    'using UiPath.CodedWorkflows;',
    '',
    'namespace SamplePerfProject',
    '{',
    `    public class ${cls} : CodedWorkflow`,
    '    {',
    '        [Workflow]',
    '        public void Execute(string inputPath)',
    '        {',
    `            Log("${cls} starting for " + inputPath);`,
    `            var apiKey = system.GetAsset("ApiKey_${i % 9}");`
  ];
  // 2-3 service calls: every third file reads one extra asset.
  if (i % 3 === 0) {
    lines.push(`            var endpoint = system.GetAsset("Endpoint_${i % 4}");`);
  }
  lines.push(
    `            var batch = ${helper}.BuildBatch(inputPath, ${(i % 13) + 3});`,
    '',
    '            if (batch.Count == 0)',
    '            {',
    `                Log("${cls}: nothing to process — aborting");`,
    '                return;',
    '            }',
    '',
    '            var processed = 0;',
    '            foreach (var item in batch)',
    '            {',
    `                var normalized = ${helper}.Normalize(item, apiKey);`,
    `                system.AddQueueItem("Queue_${i % 6}", new { Item = normalized, Index = processed });`,
    '                processed++;',
    '            }',
    '',
    `            workflows.${next}(inputPath, processed);`
  );
  if (i % 7 === 0) {
    lines.push(
      '',
      `            RunWorkflow("Legacy/Flow${i}.xaml", new { Source = inputPath, Count = processed });`
    );
  }
  if (i % 11 === 0) {
    lines.push(
      '',
      '            var dynamicTarget = "Dynamic/Flow_" + processed + ".xaml";',
      '            RunWorkflow(dynamicTarget, new { Source = inputPath });'
    );
  }
  lines.push(
    '',
    `            Log("${cls} finished — processed " + processed + " items");`,
    '        }',
    '    }',
    '}',
    ''
  );
  return lines.join('\n');
}

/** Deterministic static helper class `HelperK`. */
function helperSource(k) {
  const cls = `Helper${k}`;
  return [
    '// Generated by scripts/genSampleProject.mjs — shared helper class.',
    'using System;',
    'using System.Collections.Generic;',
    'using System.Linq;',
    '',
    'namespace SamplePerfProject',
    '{',
    `    public static class ${cls}`,
    '    {',
    '        public static List<string> BuildBatch(string inputPath, int seed)',
    '        {',
    `            return Enumerable.Range(0, seed + ${k})`,
    `                .Select(i => inputPath + "/item-" + i + "-${k}")`,
    '                .ToList();',
    '        }',
    '',
    '        public static string Normalize(string item, object apiKey)',
    '        {',
    `            return item.Trim().ToUpperInvariant() + "::${k}::" + apiKey;`,
    '        }',
    '    }',
    '}',
    ''
  ].join('\n');
}

function projectJson() {
  return `${JSON.stringify(
    {
      name: 'SamplePerfProject',
      projectVersion: '1.0.0',
      expressionLanguage: 'CSharp',
      targetFramework: 'Portable',
      entryPoints: [
        {
          filePath: ENTRY_REL_PATH,
          uniqueId: '00000000-0000-0000-0000-000000000000'
        }
      ]
    },
    null,
    2
  )}\n`;
}

/**
 * Generate the project tree under `outDir` (wiped first).  Returns the
 * number of .cs files written (n workflows + HELPER_COUNT helpers).
 */
export function generateProject(n, outDir) {
  if (!Number.isInteger(n) || n < 1) {
    throw new Error(`generateProject: n must be a positive integer, got ${n}`);
  }
  const root = resolve(outDir);
  rmSync(root, { recursive: true, force: true });
  mkdirSync(join(root, 'Workflows'), { recursive: true });
  mkdirSync(join(root, 'Helpers'), { recursive: true });

  writeFileSync(join(root, 'project.json'), projectJson());
  for (let i = 0; i < n; i += 1) {
    writeFileSync(join(root, 'Workflows', `${workflowClassName(i)}.cs`), workflowSource(i, n));
  }
  for (let k = 0; k < HELPER_COUNT; k += 1) {
    writeFileSync(join(root, 'Helpers', `Helper${k}.cs`), helperSource(k));
  }
  return n + HELPER_COUNT;
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

const isMain =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href;

if (isMain) {
  const n = Number.parseInt(process.argv[2] ?? '', 10);
  if (!Number.isInteger(n) || n < 1) {
    console.error('usage: node scripts/genSampleProject.mjs <n> [outDir=tmp-sample-project]');
    process.exit(1);
  }
  const outDir = process.argv[3] ?? 'tmp-sample-project';
  const fileCount = generateProject(n, outDir);
  console.log(
    `generated ${fileCount} .cs files (${n} workflows + ${HELPER_COUNT} helpers) ` +
      `+ project.json in ${resolve(outDir)}`
  );
}
